name: Semantic Release 

on:
  push:
	 jobs:
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.SR_TOKEN }} 
        run: npx semantic-release
      - name: Update Git remote URL
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.SR_TOKEN }}@github.com/chaitanyabatchu4/semantec.git
      - name: List tags and push to repository
        run: |
          git tag -l | xargs -I@ git push origin main