name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          # Configuring semantic-release directly via environment variables
          SEMANTIC_RELEASE_PACKAGE: '{"releaseRules":[{"type":"feat","release":"minor"},{"type":"fix","release":"patch"},{"type":"chore","release":"patch"},{"type":"docs","release":"patch"},{"type":"style","release":"patch"},{"type":"refactor","release":"patch"},{"type":"perf","release":"patch"},{"type":"test","release":"patch"}],"parserOpts":{"noteKeywords":["BREAKING CHANGE","BREAKING CHANGES"]},"branches":["main"]}'
        run: npx semantic-release
      - name: Update Git remote URL
        run: git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/chaitanyabatchu4/semantec.git
      - name: Push tags to repository
        run: git push --follow-tags origin main
