name: Semantic Release 

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.SR_TOKEN }} 
        run: npx semantic-release
      - name: Push tag to repository
        run: |
          git remote add origin https://x-access-token:${{ secrets.SR_TOKEN }}@github.com/chaitanyabatchu4/semantec.git
          git tag -l | xargs -I@ git push origin @
      - name: Test
        run: npm test
        
